server:
  max-http-header-size: 10MB
  port : 9090
  tomcat:
    threads:
      max: 1000
  connection-timeout: 60s
  servlet:
    context-path: /feedback-report

spring:
  application:
    name: feedback-report
  cloud:
    consul:
      host: ${CONSULE_HOST}
      port: ${CONSULE_PORT}
      discovery:
        service-name: feedback-report
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
  datasource:
    writer: 
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${DB_WRITE_IP}:${DB_WRITE_PORT}/alliance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        idle-timeout: 10000
        maximum-pool-size: 5
        connection-timeout: 60000
        pool-name: mailbox2
        max-lifetime: 1800000
    reader: 
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${DB_READ_IP}:${DB_READ_PORT}/alliance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        idle-timeout: 10000
        maximum-pool-size: 5
        connection-timeout: 60000
        pool-name: mailbox2
        max-lifetime: 1800000

  servlet:
    multipart:
      location: /Users/nandin.pao/Documents/workspace/poshero/mailbox/upload_tmp
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always        
