server:
  max-http-request-header-size: 10MB
  port: 9080
  tomcat:
    threads:
      max: 1000
  servlet:
    context-path: /protocol

spring:
  application:
    name: protocol
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      enabled: true
      discovery:
        service-name: protocol
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
  datasource:
    writer:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://127.0.0.1:3316/alliance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        idle-timeout: 10000
        maximum-pool-size: 5
        connection-timeout: 60000
        pool-name: sender-report2
        max-lifetime: 1800000
    reader:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://127.0.0.1:3316/alliance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        idle-timeout: 10000
        maximum-pool-size: 5
        connection-timeout: 60000
        pool-name: sender-report2
        max-lifetime: 1800000

  servlet:
    multipart:
      location: /Users/nandin.pao/Documents/workspace/poshero/sender-report/upload_tmp
      max-file-size: 10240KB
      max-request-size: 10240KB

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
