version: '3.8'

services:
  mail-admin:
    image: mail-admin
    container_name: mail-admin-node1
    build:
      context: setting
    ports:
      - "8090:80"
    restart: always
    environment:
      CONSULE_HOST: ${ip}
      CONSULE_PORT: 8500
    
   
    