server:
  port: 9060
  tomcat:
    threads:
      max: 1000

  servlet:
    context-path: /epc

spring:
  application:
    name: epc

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    consul:
      host: ${CONSULE_HOST}
      port: ${CONSULE_PORT}
      discovery:
        service-name: epc
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
  data :
    redis:
      database: 0
      password:
      timeout: 30000
      mode: cluster
      pool:
        maxIdle: 16
        minIdle: 8
        maxActive: 8
        maxWait: 3000
        connTimeout: 3000
        soTimeout: 3000
        size: 10
      single:
        address:
      cluster:
        scanInterval: 1000
        nodes: ${REDIS_HOST}
        readMode: SLAVE
        retryAttempts: 3
        failedAttempts: 3
        slaveConnection-pool-size: 64
        masterConnection-pool-size: 64
        retryInterval: 1500
      sentinel:
        master: business-master
        nodes:
        masterOnlyWrite: true
        failMax: 3

mqueue:
  artemis:
    id : EPConsumer
    server : (${QUEUE_HOST})
    user : ${QUEUE_USER}
    password : ${QUEUE_PASSWORD}
    maxConnection : 1000
    connectionTimeout : 30000
    expiryTimeout : 0
    idleTimeout : 30000
    prefetchSize : 1
    maximumActiveSessionPerConnection: 1
    connectionCheckInterval: 10000
    retryInterval: 3000
    consumers:
      - name: user-email
        poolSize: 5
        group:
      - name: user-asset
        poolSize: 5
        group:
      - name: email-schedule
        poolSize: 5
        group:
      - name: email-sender
        poolSize: 5
        group:
          - key: JMSXGroupID
            value: "gmail.com"
            poolSize: 20
          - key: JMSXGroupID
            value: "yahoo.com"
            poolSize: 20
          - key: JMSXGroupID
            value: "amazonaws.com"
            poolSize: 20
          - key: JMSXGroupID
            value: "manual.com"
            poolSize: 20
