version: '3.3'

services:
    redis-master1:
        container_name: redis-master1
        hostname: redis-master1
        restart: always
        build:
            context: redis
        volumes:
            - ./data/node1:/data
        ports: 
            - 7000:7000 
            - 17000:17000
        networks:
          agitg-network:
             ipv4_address: 172.20.0.100
        entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7000", --cluster-announce-ip, "172.20.0.100"]
    
    redis-master2:
        container_name: redis-master2
        hostname: redis-master2
        restart: always
        build:
            context: redis 
        volumes:
            - ./data/node2:/data
        ports: 
            - 7001:7001 
            - 17001:17001
        networks:
          agitg-network:
             ipv4_address: 172.20.0.101
        entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7001", --cluster-announce-ip, "172.20.0.101"]
    
    redis-master3:
        container_name: redis-master3
        hostname: redis-master3
        restart: always
        build:
            context: redis 
        volumes:
            - ./data/node3:/data
        ports: 
            - 7002:7002 
            - 17002:17002
        networks:
          agitg-network:
             ipv4_address: 192.168.2.112
        entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7002", --cluster-announce-ip ,"192.168.2.112"]
    
    redis-slave1:
        container_name: redis-slave1
        hostname: redis-slave1
        restart: always
        build:
            context: redis 
        volumes:
            - ./data/node4:/data
        ports: 
            - 7003:7003 
            - 17003:17003
        networks:
          agitg-network:
             ipv4_address: 172.20.0.103
        depends_on:
          - redis-master1
        entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7003", --cluster-announce-ip ,"172.20.0.103"]

    redis-slave2:
        container_name: redis-slave2
        hostname: redis-slave2
        restart: always
        build:
            context: redis 
        volumes:
            - ./data/node5:/data
        ports: 
            - 7004:7004 
            - 17004:17004
        networks:
          agitg-network:
             ipv4_address: 172.20.0.104
        depends_on:
          - redis-master2
        entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7004", --cluster-announce-ip ,"172.20.0.104"]
        # command: redis-server --slaveof redis-master2 7001
   
    redis-slave3:
        container_name: redis-slave3
        hostname: redis-slave3
        restart: always
        build:
            context: redis 
        volumes:
            - ./data/node6:/data
        ports: 
            - 7005:7005 
            - 17005:17005
        networks:
          agitg-network:
             ipv4_address: 172.20.0.105 
        depends_on:
          - redis-master3
        entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port, "7005", --cluster-announce-ip , "172.20.0.105"]
        # command: redis-server --slaveof redis-master3 7002
    
    redis-cluster-creator:
        container_name: redis-cluster-creator
        image: redis
        entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create 172.20.0.100:7000 172.20.0.101:7001 192.168.2.112:7002 172.20.0.103:7003 172.20.0.104:7004 172.20.0.105:7005 --cluster-replicas 1']
        depends_on: 
          - redis-master1 
          - redis-master2
          - redis-master3 
          - redis-slave1
          - redis-slave2
          - redis-slave3
        networks:
          - agitg-network

    redis-sentinel1:
        container_name: redis-sentinel1
        build: sentinel
        depends_on:
          - redis-master1
          - redis-master2
          - redis-master3

    redis-sentinel2:
        container_name: redis-sentinel2
        build: sentinel
        depends_on:
          - redis-master1
          - redis-master2
          - redis-master3

    redis-sentinel3:
        container_name: redis-sentinel3
        build: sentinel
        depends_on:
          - redis-master1
          - redis-master2
          - redis-master3

networks:
    agitg-network:
      external:
        name: agitg-network