server:
  max-http-request-header-size: 10MB
  port : 9020
  servlet:
    context-path: /mailbox

spring:
  application:
    name: mailbox
  cloud:
    consul:
      host: ${CONSULE_HOST}
      port: ${CONSULE_PORT}
      discovery:
        service-name: mailbox
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
  datasource:
    writer: 
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${DB_WRITE_IP}:${DB_WRITE_PORT}/alliance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        idle-timeout: 10000
        maximum-pool-size: 5
        connection-timeout: 60000
        pool-name: mailbox2
        max-lifetime: 1800000
    reader: 
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://${DB_READ_IP}:${DB_READ_PORT}/alliance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        idle-timeout: 10000
        maximum-pool-size: 5
        connection-timeout: 60000
        pool-name: mailbox2
        max-lifetime: 1800000

  data :
    redis:
      database: 0
      password:
      timeout: 30000
      mode: cluster
      pool:
        maxIdle: 16
        minIdle: 8
        maxActive: 8
        maxWait: 3000
        connTimeout: 3000
        soTimeout: 3000
        size: 10
      single:
        address:
      cluster:
        scanInterval: 1000
        nodes: ${REDIS_HOST}
        readMode: SLAVE
        retryAttempts: 3
        failedAttempts: 3
        slaveConnection-pool-size: 64
        masterConnection-pool-size: 64
        retryInterval: 1500
      sentinel:
        master: business-master
        nodes:
        masterOnlyWrite: true
        failMax: 3
  
    servlet:
      multipart:
        location: /Users/nandin.pao/Documents/workspace/poshero/mailbox/upload_tmp
        max-file-size: 10240KB
        max-request-size: 10240KB

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always        
